### ISSUE TITLE
Could Grasper run in clusters that do not support RDMA?

### ISSUE THREAD

**Issue by RuiRitaYang** [yaobaiwei/Grasper#4]
Dear authors,

I'm pretty interested in the Grasper paper and would like to try it by myself. I noticed that in the grasper-conf.ini, there is one option with USE_RDMA = true. Does this mean that Grasper can run purely without RDMA support?

Also, does Grasper has a tutorial for a standalone version? The installation instruction seems for a cluster mode version (that G-Miner Deployment instruction). If not, do we have a docker image that users can play with?

Thanks a lot in advance and great work!

Regards,
-Rui

**Comment by yaobaiwei** [comment]
Hi, Rui:
      Yes, Grasper can be deployed on normal network environment and run on single-machine setting (no matter launching multiple instances or only one).
      You can build it first and run as a try. If you meet any problem, please let me know:)
Thanks!

Best,
Hongzhi CHEN

Rui Yang ***@***.***> 于 2021年3月17日周三 上午11:17写道：

**Comment by RuiRitaYang** [comment]
Hi Hongzhi,

Thanks a lot! I've tried to build Grasper in Docker (single node) and I've attached the error log that I'm facing.
When I built the dependencies, I used some alternative link since some provided link is deprecated or it didn't work when I tried. So I install some packages through apt install, but I also update the CMake files accordingly. 
However, when I compile grasper, there are some errors prompted (but seems like some errors are not related to dependencies). Please let me know if the dependency information is needed to fix the compiling problems. 

(A minor extra change is I've added a "include <cassert>" into base/node.hpp since there are multiple error: "'assert' was not declared in this scope" for that file.

Here is the [log information](https://gist.github.com/RuiRitaYang/1d9d264ca8514484dd0dc0578fd09208) for building error.
Do you have any suggestions about how those can be fixed? 

Thanks a lot in advance!

Regards,
-Rui

**Comment by yaobaiwei** [comment]
Hi, Yang:
      I took a briefly view on the log. I think some error infos were caused by a new GCC version, which can be easily fixed by "Google".
      But I noticed that the last error is about UNTIL expert, I approved one PR from my previous MSC student about that functionality after my graduation. Can you try to rollback the repo version to the last commit point to check if it is caused by that PR?
      If so, you can reset to that version. Sorry that I've graduated and now working in industry. It's a bit hard for me to find some specific time to reproduce the environment and test it. But I am sure that the release version of grasper works well. If you still meet the same problem after rollback, I will contract my workmates who still stay at cuhk to help you
address it.
     This is a fast response from Hongzhi.

Best,


Rui Yang ***@***.***> 于 2021年3月29日周一 上午11:42写道：

**Comment by RuiRitaYang** [comment]
Hi Hongzhi,

Thanks a lot for these suggestions! We'll have a try on the version before the PR and change the GCC version. Hope it can work directly!

Regards,
-Rui

**Comment by RuiRitaYang** [comment]
Hi Hongzhi,

Thanks a lot for your help! I've downgraded g++ and gcc to 5.3.1, and build on top of SOCC release version (the first commit), but I'm still facing trouble building it.

If I directly compile after changing the CMAKELists, it will build with log [here](https://gist.github.com/RuiRitaYang/dcae4ae178f0b4eabd42f634626e293e), which has errors as assert. I could fix this by adding #include<cassert> in the base/ node.hpp. However, I feel that release should work without any code change right? So is gcc-5 still too new for Grasper? If so could I which exact version you used?

OTOH, if I added the #inlude<cassert>, I'll face linking issue (for MKL), with log [here](https://gist.github.com/RuiRitaYang/4ed7f92e75ea766a415f9bb21843772f). The error happens related to mkl.  Since Grasper README does not mention MKL version, so I installed mkl directly through apt install intel-mkl. Do you have any suggestions about how to fix it?

Thanks for building such a great work as Grasper! I totally understand that you've graduated and don't have enough time to help with your own work. But any suggestion will be helpful, and it'd also be great if you can forward me to someone who's still working on the project. It'd be great to see how Grasper can be re-built other than the original paper experiment environment.

Thanks a lot!

Regards,
-Rui

**Comment by flint-stone** [comment]
Hi Hongzhi:

Thanks for helping us! I'm working with Rui to deploy Grasper in the linux environment and I'm seeing the same issue in my setting: Essentially the issues are related to 

-  error: ‘constexpr’ needed for in-class initialization of static data member ‘const double IndexStore::ratio’ of non-integral type [-fpermissive] (index_store.hpp:17)
- error: passing ‘const ibinstream’ as ‘this’ argument discards qualifiers [-fpermissive] (rdma_mailbox.cpp:89)
- error: return-statement with a value, in function returning 'void' (parser.cpp:158)

(using gcc 5 may create the following problem, which I suspect it is because we are using a newer version of some library which cause ambiguous call)

- In static member function ‘static std::__cxx11::string Tool::DebugString(value_t&)’: (tool.hpp:350)


I have tried gcc 4, 5 and 7 and these three issues are the issues that persist. If you happen to anyone who's maintaining the project please don't hesitate to let us know so that we could reach them directly!



Thanks!

**Comment by yaobaiwei** [comment]
Hi, Rui:
      Sorry for the delayed reply. I will forward the context to my
workmates in Grasper and let them help you to address the issue ASAP.
Thanks!

Best,


Rui Yang ***@***.***> 于 2021年3月31日周三 上午3:58写道：

**Comment by yaobaiwei** [comment]
Hi, Xu:
      Sorry for the late reply as I only weekly check this email account
now. Actually, I've told Rui that I would forward the related context to my
workmates in Grasper proj who are still at CUHK. I believe them can help
your team address the problem soon via checking which gcc we used at the
lab.
Thanks!

Best,
Hongzhi

Le Xu ***@***.***> 于 2021年3月31日周三 上午9:32写道：

**Comment by yaobaiwei** [comment]
> Hi Hongzhi:
> 
> Thanks for helping us! I'm working with Rui to deploy Grasper in the linux environment and I'm seeing the same issue in my setting: Essentially the issues are related to
> 
> * error: ‘constexpr’ needed for in-class initialization of static data member ‘const double IndexStore::ratio’ of non-integral type [-fpermissive] (index_store.hpp:17)
> * error: passing ‘const ibinstream’ as ‘this’ argument discards qualifiers [-fpermissive] (rdma_mailbox.cpp:89)
> * error: return-statement with a value, in function returning 'void' (parser.cpp:158)
> 
> (using gcc 5 may create the following problem, which I suspect it is because we are using a newer version of some library which cause ambiguous call)
> 
> * In static member function ‘static std::__cxx11::string Tool::DebugString(value_t&)’: (tool.hpp:350)
> 
> I have tried gcc 4, 5 and 7 and these three issues are the issues that persist. If you happen to anyone who's maintaining the project please don't hesitate to let us know so that we could reach them directly!
> 
> Thanks!

We've confirmed that the last merged PR indeed got some problems. We will rollback. @Aaronchangji please help to check which GCC version we used in the Lab's workspace.

**Comment by Aaronchangji** [comment]
> > Hi Hongzhi:
> > Thanks for helping us! I'm working with Rui to deploy Grasper in the linux environment and I'm seeing the same issue in my setting: Essentially the issues are related to
> > 
> > * error: ‘constexpr’ needed for in-class initialization of static data member ‘const double IndexStore::ratio’ of non-integral type [-fpermissive] (index_store.hpp:17)
> > * error: passing ‘const ibinstream’ as ‘this’ argument discards qualifiers [-fpermissive] (rdma_mailbox.cpp:89)
> > * error: return-statement with a value, in function returning 'void' (parser.cpp:158)
> > 
> > (using gcc 5 may create the following problem, which I suspect it is because we are using a newer version of some library which cause ambiguous call)
> > 
> > * In static member function ‘static std::__cxx11::string Tool::DebugString(value_t&)’: (tool.hpp:350)
> > 
> > I have tried gcc 4, 5 and 7 and these three issues are the issues that persist. If you happen to anyone who's maintaining the project please don't hesitate to let us know so that we could reach them directly!
> > Thanks!
> 
> We've confirmed that the last merged PR indeed got some problems. We will rollback. @Aaronchangji please help to check which GCC version we used in the Lab's workspace.

GCC version: `5.2.0`
MKL version and environment:

>Major version:          2017
Minor version:            0
Update version:          4
Build:                          20170811
Platform:                    Intel(R) 64 architecture
Processor optimization:  Intel(R) Streaming SIMD Extensions 4.2 (Intel(R) SSE4.2) enabled processors

**Comment by RuiRitaYang** [comment]
Hi Hongzhi and Changji，

Thanks a lot for providing all the information! We've successfully install gcc 5.2.1 and MKL 2017.0.5:239. We have also tried a few mkl versions right before and after it. However, we are still facing the same linking error in my last post (log [here](https://gist.github.com/RuiRitaYang/4ed7f92e75ea766a415f9bb21843772f). More specifically, it shows: 

[100%] Linking CXX executable ../../release/server
/usr/bin/ld: liball-deps.a(mkl_util.cpp.o): in function `std::MKLUtil::Test()':
mkl_util.cpp:(.text+0x59): undefined reference to `vslNewStream'
/usr/bin/ld: mkl_util.cpp:(.text+0x93): undefined reference to `vdRngGaussian'
/usr/bin/ld: mkl_util.cpp:(.text+0xc6): undefined reference to `vslDeleteStream'
/usr/bin/ld: liball-deps.a(mkl_util.cpp.o): in function `std::MKLUtil::UniformRNGI4(int*, int, int, int)':
mkl_util.cpp:(.text+0x138): undefined reference to `viRngUniform'
/usr/bin/ld: liball-deps.a(mkl_util.cpp.o): in function `std::MKLUtil::UniformRNGF4(float*, int, float, float)':
mkl_util.cpp:(.text+0x15e): undefined reference to `vsRngUniform'
/usr/bin/ld: liball-deps.a(mkl_util.cpp.o): in function `std::MKLUtil::UniformRNGF8(double*, int, double, double)':
mkl_util.cpp:(.text+0x17e): undefined reference to `vdRngUniform'
/usr/bin/ld: liball-deps.a(mkl_util.cpp.o): in function `std::MKLUtil::MKLUtil(int)':
mkl_util.cpp:(.text+0x17): undefined reference to `vslNewStream'
collect2: error: ld returned 1 exit status
make[2]: *** [driver/CMakeFiles/server.dir/build.make:90: ../release/server] Error 1
make[1]: *** [CMakeFiles/Makefile2:453: driver/CMakeFiles/server.dir/all] Error 2
make: *** [Makefile:84: all] Error 2

We attempted cmake flags suggested online or other potential fixes but none of them works. So could you help to take a look what are the problems? The code we use is the SoCC release version (the very first commit) since that was the first release. We deployed Grasper in docker, and the image can be downloaded via `docker pull ruiritayang/grasper:v3`. Could you help to take a look if possible? We'll sincerely appreciate it!

Besides, the Grasper paper mentions the experiments with a few LDBC queries. Could we know whether you still have those query implementations on Grasper? It'd be great if you don't mind sharing them. We'll appreciate it a lot!

Thanks again in advance!

Regards,
-Rui

**Comment by yaobaiwei** [comment]
> Hi Hongzhi and Changji，
> 
> Thanks a lot for providing all the information! We've successfully install gcc 5.2.1 and MKL 2017.0.5:239. We have also tried a few mkl versions right before and after it. However, we are still facing the same linking error in my last post (log [here](https://gist.github.com/RuiRitaYang/4ed7f92e75ea766a415f9bb21843772f). More specifically, it shows:
> 
> [100%] Linking CXX executable ../../release/server
> /usr/bin/ld: liball-deps.a(mkl_util.cpp.o): in function `std::MKLUtil::Test()': mkl_util.cpp:(.text+0x59): undefined reference to `vslNewStream'
> /usr/bin/ld: mkl_util.cpp:(.text+0x93): undefined reference to `vdRngGaussian' /usr/bin/ld: mkl_util.cpp:(.text+0xc6): undefined reference to `vslDeleteStream'
> /usr/bin/ld: liball-deps.a(mkl_util.cpp.o): in function `std::MKLUtil::UniformRNGI4(int*, int, int, int)': mkl_util.cpp:(.text+0x138): undefined reference to `viRngUniform'
> /usr/bin/ld: liball-deps.a(mkl_util.cpp.o): in function `std::MKLUtil::UniformRNGF4(float*, int, float, float)': mkl_util.cpp:(.text+0x15e): undefined reference to `vsRngUniform'
> /usr/bin/ld: liball-deps.a(mkl_util.cpp.o): in function `std::MKLUtil::UniformRNGF8(double*, int, double, double)': mkl_util.cpp:(.text+0x17e): undefined reference to `vdRngUniform'
> /usr/bin/ld: liball-deps.a(mkl_util.cpp.o): in function `std::MKLUtil::MKLUtil(int)': mkl_util.cpp:(.text+0x17): undefined reference to `vslNewStream'
> collect2: error: ld returned 1 exit status
> make[2]: *** [driver/CMakeFiles/server.dir/build.make:90: ../release/server] Error 1
> make[1]: *** [CMakeFiles/Makefile2:453: driver/CMakeFiles/server.dir/all] Error 2
> make: *** [Makefile:84: all] Error 2
> 
> We attempted cmake flags suggested online or other potential fixes but none of them works. So could you help to take a look what are the problems? The code we use is the SoCC release version (the very first commit) since that was the first release. We deployed Grasper in docker, and the image can be downloaded via `docker pull ruiritayang/grasper:v3`. Could you help to take a look if possible? We'll sincerely appreciate it!
> 
> Besides, the Grasper paper mentions the experiments with a few LDBC queries. Could we know whether you still have those query implementations on Grasper? It'd be great if you don't mind sharing them. We'll appreciate it a lot!
> 
> Thanks again in advance!
> 
> Regards,
> -Rui

@RuiRitaYang : Hi, Rui:
     Checked your log. The impl of our MKLUtil failed to find the ref of some func (e.g., viRngUniform) from mkl lib, which means that Grasper failed to link to mkl lib correctly in your installation, please make use that CMake can find mkl lib successfully by seeying correctly:
`# MKL
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -I${MKL_ROOT}/mkl/include") 
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -L${MKL_ROOT}/mkl/lib/intel64") 
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -lmkl_blas95_lp64 -lmkl_lapack95_lp64 -lmkl_intel_lp64 -lmkl_sequential -lmkl_core ")`

@Aaronchangji Could you help to send our `LDBC impl` (i.e., the query template strings) to Rui if the expr version still remains?

**Comment by RuiRitaYang** [comment]
Hi Hongzhi, 

Thanks a lot! I feel we are using  the correct path and also the code you mentioned in CMake. In the mkl dir we put as root, we can grep the func (e.g. viRngUniform) in the include folder. However,  it still cannot link. That's why we provided our docker image and hope for some suggestions if possible.

Thanks a lot for your help!

Regards,
-Rui

**Comment by Aaronchangji** [comment]
Here is our implementations of LDBC queries used in our paper. [Grasper_LDBC_Impl.txt](https://github.com/yaobaiwei/Grasper/files/6291169/Grasper_LDBC_Impl.txt)
